---
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(collapse  = TRUE,
                      comment   = "#>",
                      fig.path  = "man/figures/",
                      out.width = "100%")
```

# Repository for XXX Inventorying paper

<!-- badges: start -->

[![License: GPL (\>=
2)](https://img.shields.io/badge/License-GPL%20%28%3E%3D%202%29-blue.svg)](https://choosealicense.com/licenses/gpl-2.0/)

<!-- badges: end -->

### Description

This is the Research Compendium of **XXX Inventorying XXX**. It contains
the necessary codes to reproduce all analyses and plot images in the
article. Scripts are numerically ordered, that is, the workflow starts
with `01_downloading_data.R` and ends with `05_plotting_data.R`. There
is a single internal function, `99_summInv.R`, that is loaded with
`devtools::load_all()` to summarise forest inventory data by vegetation
type.

<br />

### Workflow

Codes are structured as follows:

1.  **Downloading data**: the script `01_downloading_data.R` gets FURB
    herbarium occurrences from JBRJ IPT as a DarwinCore sheet. FURB
    herbarium data from JABOT, however, needs to be manually downloaded.
    Instructions are commented in the script. <br /> <br />
2.  **Preparing data**: the script `02_preparing_data.R` loads, edits,
    and cleans, and saves the data from both the forest and floristic
    inventory of FlorestaSC project. Script `03_preparing_lifeforms.R`
    extracts the register life form from a field called *projeto* in the
    JABOT spreadsheet. This is not a DwC standardized field, so it
    cannot be extracted directly from JBRJ IPT. See **Downloading
    data**. All steps for both scripts are thoroughly described within
    it, as comments. <br /> <br />
3.  **Summarizing data**: the script `04_summarizing_data.R` loads the
    previously saved data and performs all types of operations to sum up
    our results. <br /> <br />
4.  **Plotting data**: finally, the script `05_plotting_data.R` creates
    all the plots shown in the main article, plus a few extra
    summarizations.

<br />

### How to cite

Please cite this GiHub as:

> **{{ ADD A CITATION }}**

<br />

### References
